### ISSUE TITLE
Doesn't appear to work with XWayland

### ISSUE THREAD

**Issue by jekstrand** [Think-Silicon/GLOVE#10]
I can't seem to get any applications working with XWayland.  I've tried gfxbench 5 trex benchmark, es2gears_x11 from mesa-demos, and wflinfo.  So far, none of them can successfully create a context with XWayland.  Some of them seem to at least somewhat work on bare X11, however.

**Comment by kvarcg** [comment]
Thank you for raising this issue. Currently, only X11 is supported. Wayland support (as well as other modes) are on our TODO list. I will keep this issue open to post any future updates.

In the meantime, it would greatly help our implementation/testing process if you could you provide us with any findings regarding any applications that suffer from odd behaviour/crashes/etc even on pure X11.

**Comment by jekstrand** [comment]
I understand that it doesn't work with Wayland.  However, the fact that it doesn't work with XWayland surprised me.  It should, by and large, just look like a regular X server with DRI3.

**Comment by dgeorg79** [comment]
GLOVE now supports Wayland. I also tested GLOVE demos with XWayland, and it seems they work
