### ISSUE TITLE
eglGetProcAddress not implemented

### ISSUE THREAD

**Issue by jekstrand** [Think-Silicon/GLOVE#11]
This prevents waffle (https://github.com/waffle-gl/waffle) from working at all.

**Comment by dgeorg79** [comment]
This is in TODO list for long time but it seems we have good reasons to raise the priority. 

Let's keep this issue open to track the progress.

Thanks for letting us know!

**Comment by kvarcg** [comment]
Support for eglGetProcAddress has been added. I am closing this, but let us know if you find any issues.
