### ISSUE TITLE
Test GLOVE on NVIDIA GPU

### ISSUE THREAD

**Issue by dgeorg79** [Think-Silicon/GLOVE#19]

**Comment by abasilak** [comment]
GLOVE has been successfully tested on a **NVIDIA  GTX 670** graphics card with the following configuration: 
-  Drivers version: _396.54_, Vulkan API version: _1.1.70_, OS: _Ubuntu 18.04.1 LTS_

**Comment by abasilak** [comment]
GLOVE has been successfully tested on a **NVIDIA GeForce 940M** graphics card with the following configuration:

- Drivers version: _396.51_, Vulkan API version: _1.1.70_, OS: _Ubuntu 16.04.1 LTS_
