### ISSUE TITLE
The **index** that is not allocated by calling `Allocate()` is treaded the same as normal OpenGL handle. Is that a bug?

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#22]
Repeat title:
The **index** that is not allocated by calling `Allocate()` is treaded the same as normal OpenGL handle. Is that a bug?

https://github.com/Think-Silicon/GLOVE/blob/76e192f8b640fdbd742271f78ba9deaf36767ff8/GLES/source/utils/arrays.hpp#L97

**Comment by kvarcg** [comment]
Thank you for raising this issue. Could you clarify a bit more what the bug seems to be?

**ObjectArray::Allocate** is called by **glGen***, while **GetObject** is called during instantiation of objects (for generated names)
There is an issue here, as **Allocate** does not take into account the generated ids, but this will be fixed soon.

**Comment by Michael-Lfx** [comment]
When an outside caller pass an id to us which is greater than 0 but not generated by calling `ObjectArray::Allocate` namely not by `glGen*`, however we will take it as a valid one and create a backing object for it. In short ids namely handles only create by `glGen*` family is valid not a random one greater than 0. I didn't see any filter to process that illegal case. Here is an abuse example.

```
// no call to glGenTextures
// 6 is not generated by us, user think it is ok and pass it carelessly. 
// `glGenTextures` is the only way to get handles, right?
glBindTexture(GL_TEXTURE_2D, 6); 
glTexImage2D(...)
```

**Comment by kvarcg** [comment]
According to the spec glBind* also handles name creation.
Therefore, it is valid to call **glBindTexture(GL_TEXTURE_2D, 6);** without calling **glGenTextures**. In that case, however, **glGenTextures** will not return 6 as long as the texture is in use.
We had a bug that did not guarantee the last part but it was fixed a few moments ago.
See also [glGenTextures](http://docs.gl/es2/glGenTextures) and [glBindTexture](http://docs.gl/es2/glBindTexture).
