### ISSUE TITLE
Missing process about non active object case.

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#23]
Should we return when `GetActiveTexture(target)` return `nullptr`? Here is the case that user wrongly reset the active object to 0 (default value) and call this function. Will it be wild pointer?

https://github.com/Think-Silicon/GLOVE/blob/02a78cf566eafaf5900b12f9c75bf6b4cb0167de/GLES/source/context/contextTexture.cpp#L207

**Comment by abasilak** [comment]
No it is not a wild pointer.

When we reset the active object to 0 (e.g. //glBindTexture(0)//), we bind it to the default texture (created at the initialization of the context) :
https://github.com/Think-Silicon/GLOVE/blob/02a78cf566eafaf5900b12f9c75bf6b4cb0167de/GLES/source/context/contextTexture.cpp#L70

Similarly, we have also cover the case when a texture is going to be deleted. We check if the texture is currently active by iterating through all the active textures units and if yes, we bind it to the default texture.
https://github.com/Think-Silicon/GLOVE/blob/02a78cf566eafaf5900b12f9c75bf6b4cb0167de/GLES/source/context/contextTexture.cpp#L120
