### ISSUE TITLE
Is there no need to implement thread related EGL instance?

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#24]
Based on the fellowing links. I have noticed that parameter `eglShareContext` of `RenderingThread::CreateContext` is ignored. Hence there is no `shared` EGL instance to be created? Every call to `eglCreateContext` just creates a brand new instance of `EGLContext_t`, is that right?

https://github.com/Think-Silicon/GLOVE/blob/1bf8bd5fb9752ec82a88a19ba4494faf624b4032/EGL/source/api/egl.cpp#L37
https://github.com/Think-Silicon/GLOVE/blob/1bf8bd5fb9752ec82a88a19ba4494faf624b4032/EGL/source/thread/renderingThread.cpp#L181

Moreover, I am confused by the line `EGLContext_t::GetEGLContext(eglContext);`. I find that it just push things to the `globalEGLContextList`. But there is no instance reuse or cache strategy like LRU of `globalEGLContextList`. What's the meaning of `globalEGLContextList` related things?

Any help is appreciated.

**Comment by kvarcg** [comment]
Thank you for raising this issue.
The current EGL implementation has limited functionality at this point, i.e., multiple threads/contexts and shared contexts are partially or not yet implemented. It is on our short-term TODO list.

The `globalEGLContextList` serves as a container for error handling, e.g., EGL_BAD_CONTEXT and is not related to the above missing features.
