### ISSUE TITLE
Is that redundant to validate `target` of object?

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#25]
Within `glBind*` series methods, the underlying instance of the `id` has been created and signed to the `target`. Therefore it’s a **valid** GL object.

Here we are sure that the object is valid because we find it in our `Array`. So... Is that redundant to validate `target` of object in all the `glIs*` methods?

https://github.com/Think-Silicon/GLOVE/blob/d442626967eafc677412141e918065b321e41702/GLES/source/context/contextFrameBuffer.cpp#L334

**Comment by abasilak** [comment]
Thanks for raising this issue.

I think that you are right...but first we have to double check if this solution is good (via our CI platform) before removing the redundant validation check from all _glIs*_ functions.

**Comment by Michael-Lfx** [comment]
If it turns out to be right, can I have the pleasure to submit a PR to that for thanking your guys making it open source project? @abasilak

**Comment by abasilak** [comment]
Yes of course. I will let you know...

**Comment by abasilak** [comment]
You can proceed. No issues raised when I performed the proposed solution (remove target validity) in the following code:

- https://github.com/Think-Silicon/GLOVE/blob/d442626967eafc677412141e918065b321e41702/GLES/source/context/contextBufferObject.cpp#L186

- https://github.com/Think-Silicon/GLOVE/blob/d442626967eafc677412141e918065b321e41702/GLES/source/context/contextFrameBuffer.cpp#L334

- https://github.com/Think-Silicon/GLOVE/blob/d442626967eafc677412141e918065b321e41702/GLES/source/context/contextRenderBuffer.cpp#L178

- https://github.com/Think-Silicon/GLOVE/blob/d442626967eafc677412141e918065b321e41702/GLES/source/context/contextTexture.cpp#L327

PS: Please add in the commit message the issue number (#issue).
