### ISSUE TITLE
Will it be multiple hint modes in the future like OpenGL ES 3.2?

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#28]
Should we change `mHintModes[]` to `mHintModes` if no other hint modes in higher GL ES versions?

https://github.com/Think-Silicon/GLOVE/blob/24696f747b467ae1a3fc34ef2e582de1bfc1caa5/GLES/source/state/stateHintAspects.h#L30

**Comment by abasilak** [comment]
We are mainly aiming for OpenGL ES 2.0 at the current moment, however support for higher versions is on our future TODO list. Thus, `GL_FRAGMENT_SHADER_DERIVATIVE_HINT` hint mode could be added in the `mHintModes[]` array...
