### ISSUE TITLE
Is currentContext missing thread safe process?

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#29]
According to the [previous issue](https://github.com/Think-Silicon/GLOVE/issues/24#issuecomment-428476182) discussed with @kvarcg , multithread support is on the agenda. Is currentContext missing thread safe process when introducing multithread? There are not lock in `SetCurrentContext(...)` and `GetCurrentContext()` now.

https://github.com/Think-Silicon/GLOVE/blob/6f5d95319af884395c03353127b3241d382d6710/GLES/source/context/context.cpp#L27

**Comment by kvarcg** [comment]
Yes, thread safety is not guarranted at this point. Also see [KnownIssues.md](https://github.com/Think-Silicon/GLOVE/blob/master/Docs/KnownIssues.md) for more details on the most important issues/missing features.

**Comment by dgeorg79** [comment]
This will be resolved with #32 which is currently running. Please watch the latter.
