### ISSUE TITLE
glslang::TProgram has no member named getUniformStages()

### ISSUE THREAD

**Issue by 1ace** [Think-Silicon/GLOVE#3]
```
Building CXX object GLES/source/CMakeFiles/GLESv2.dir/glslang/glslangShaderCompiler.cpp.o
GLES/source/glslang/glslangShaderCompiler.cpp: In member function ‘void GlslangShaderCompiler::CompileUniforms(const glslang::TProgram*)’:
GLES/source/glslang/glslangShaderCompiler.cpp:455:43: error: ‘const class glslang::TProgram’ has no member named ‘getUniformStages’; did you mean ‘getUniformName’?
         const shader_type_t stage = prog->getUniformStages(i) == (EShLangVertexMask | EShLangFragmentMask) ? static_cast<shader_type_t>(SHADER_TYPE_VERTEX | SHADER_TYPE_FRAGMENT) :
                                           ^~~~~~~~~~~~~~~~
                                           getUniformName
GLES/source/glslang/glslangShaderCompiler.cpp:456:43: error: ‘const class glslang::TProgram’ has no member named ‘getUniformStages’; did you mean ‘getUniformName’?
                                     prog->getUniformStages(i) == EShLangVertexMask ? SHADER_TYPE_VERTEX : SHADER_TYPE_FRAGMENT;
                                           ^~~~~~~~~~~~~~~~
                                           getUniformName
```

Using GLOVE 3a054883000875e2c3ca

**Comment by de2nis** [comment]
Khronos glslang master branch commit 'f556e5da2623d2a0f43d964f32a27ae510e06592' added this member method. The checkout command that is used in the scripts is using a commit after this one. Are you using custom glslang?

**Comment by 1ace** [comment]
Sorry, forgot to say; using the latest glslang release:
https://github.com/KhronosGroup/glslang/releases/tag/6.2.2596

I see that [f556e5da2623d2a0f43d964f32a27ae510e06592](https://github.com/KhronosGroup/glslang/commit/f556e5da2623d2a0f43d964f32a27ae510e06592) is not in any release yet; I'll try with a build of glslang master now and try again.

Thanks!

**Comment by 1ace** [comment]
OK, issue solved, although now I'm hitting an issue with gtest; I solved it by using dynamic linking; should I send a pull request with this patch or did you have a reason not to do that?

````
diff --git a/GLES/unitTests/CMakeLists.txt b/GLES/unitTests/CMakeLists.txt
index ec62f3a560efd608ca64..ea118f1386409bfe5b2a 100644
--- a/GLES/unitTests/CMakeLists.txt
+++ b/GLES/unitTests/CMakeLists.txt
@@ -22,11 +22,11 @@ link_directories(${GTEST_PATH}/lib
                  ${CMAKE_BINARY_DIR}/GLES/source
                  ${CMAKE_INSTALL_FULL_LIBDIR})
 
-add_library(gtest_main STATIC IMPORTED)
-set_target_properties(gtest_main PROPERTIES IMPORTED_LOCATION ${GTEST_PATH}/lib/libgtest_main.a)
+add_library(gtest_main SHARED IMPORTED)
+set_target_properties(gtest_main PROPERTIES IMPORTED_LOCATION ${GTEST_PATH}/lib/libgtest_main.so)
 
-add_library(gtest STATIC IMPORTED)
-set_target_properties(gtest PROPERTIES IMPORTED_LOCATION ${GTEST_PATH}/lib/libgtest.a)
+add_library(gtest SHARED IMPORTED)
+set_target_properties(gtest PROPERTIES IMPORTED_LOCATION ${GTEST_PATH}/lib/libgtest.so)
 
 add_executable(arrays_tests ${SOURCES})
 target_link_libraries(arrays_tests ${LIBS})
````

**Comment by de2nis** [comment]
It's nice to hear you solved the issue. Checking out at a release tag is on todo list, as soon as any is available (including this commit).
For the second issue now, I suppose you used custom googletest too, am I right?
Could you explain what problem occurred with gtest? Do you really think dynamic linking is needed?

**Comment by 1ace** [comment]
Looks like I'm unable to read instruction :see_no_evil:
I saw a CMakeList.txt so I ran `cmake`, instead of running `./update_external_sources.sh` and `./configure.sh`.

I don't have time anymore to test it by running it properly today, but I'll give it a go next week. Thanks!
