### ISSUE TITLE
if statement has identical branches

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#42]
`if` statement has identical branches with `else`.

https://github.com/Think-Silicon/GLOVE/blob/9004ae416dec8ea1a42db049964a2f25a5f8635f/GLES/source/vulkan/image.cpp#L89

**Comment by abasilak** [comment]
Statement `props.optimalTilingFeatures & flagbits` is different from `props.linearTilingFeatures  & flagbits`.

**Comment by Michael-Lfx** [comment]
Thanks for reply so quickly. But `else if` is the same as `else`.
```
else if (props.optimalTilingFeatures & flagbits) {
    mVkImageTiling = VK_IMAGE_TILING_OPTIMAL;
}
else {
    // Format not supported
    mVkImageTiling = VK_IMAGE_TILING_OPTIMAL;
}
```

**Comment by abasilak** [comment]
There is a possibility that for the given format, hardware does not support any tiling type. This is there for supporting Android platforms where we encounter this issue (: yes, a comment is missing).

We will remove it in a future, more stable, release. Thanks.
