### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#44]
In order to make PRs more convenient and safe to merge, I think that adding CI support such as [travis-ci](https://travis-ci.org) or [appveyor](https://www.appveyor.com) is helpful.

**Comment by dgeorg79** [comment]
This is, indeed, necessary to add in GLOVE. I'm adding this issue to the currently running Project (GLOVE v0.4)

**Comment by dgeorg79** [comment]
completed with 395e74a6c6e6622e60d5f0dc5ed5a2abd9b22321

**Comment by Michael-Lfx** [comment]
Thank you!
