### ISSUE TITLE
Replace raw pointer with C++ 11 smart pointer

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#47]
GLOVE is using raw pointer currently. But it brings complexity to maintain memory management. Is that any plan for introducing C++ 11 smart pointer such as std::shared_ptr and std::unique_ptr to make a better life?

**Comment by dgeorg79** [comment]
I agree with you, it would be nice to benefit from some nice C++11 features, like smart pointer. However, since this requires a big scale refactoring, we're skipping for the moment, as the main goal for the moment is full OpenGL ES 2.0 feature set. Improvements like this will come later.
