### ISSUE TITLE
mUsage of BufferObject is ignored

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#48]
Currently `mUsage` of BufferObject has no effect to the creation of `vulkanAPI::Memory` and `vulkanAPI::Buffer`. Is there any plan to make it work?

https://github.com/Think-Silicon/GLOVE/blob/54d98bfa79383cdc2714e706555dd11bfb70e604/GLES/source/resources/bufferObject.h#L37

**Comment by abasilak** [comment]
`mUsage` is a _hint_ to the GL implementation as to how a buffer object's data store will be accessed. We haven't found any Vulkan-related flag/state that could trigger driver to make more intelligent decisions that may significantly impact buffer object performance.

Despite the missing functionality, the ES2.0 conformance tests that are related to the available usage pattern of the data store (GL_STREAM_DRAW, GL_STATIC_DRAW, or GL_DYNAMIC_DRAW) have been successfully completed.
