### ISSUE TITLE
Move glClear implementation during the creation of Renderpass

### ISSUE THREAD

**Issue by kvarcg** [Think-Silicon/GLOVE#5]
glClear is currently implemented via VkClearAttachment and vkCmdClearAttachments in the clearPass object. Ideally, the clear operation should be performed via VkAttachmentLoadOp during the initialization of the "main" renderpass. This will allow glClear to work properly with glColorMask.

**Comment by dgeorg79** [comment]
Solved with commit https://github.com/Think-Silicon/GLOVE/commit/6fdee3f91f4c7e93ee0b1952440bfb1761e7b3d8

**Comment by abasilak** [comment]
> This will allow glClear to work properly with glColorMask.

Unfortunately, no for all cases. A new issue is up for solving that: #20.
