### ISSUE TITLE
Skip copy data when default texture is active

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#51]
```c++
void Context::TexImage2D(...)
{
    //...
    if(mWriteFBO->IsInDrawState()) {
        Finish();
    }

    // copy the buffer contents to the texture
    Texture *activeTexture = mStateManager.GetActiveObjectsState()->GetActiveTexture(target);
    GLint layer = (target == GL_TEXTURE_2D) ? 0 : target - GL_TEXTURE_CUBE_MAP_POSITIVE_X;
    activeTexture->SetState(width, height, level, layer, format, type, mStateManager.GetPixelStorageState()->GetPixelStoreUnpack(), pixels);

    if(activeTexture->IsCompleted()) {
        // pass contents to the driver
        activeTexture->Allocate();
    }
}
```

Currently there is no validation check for default texture. Here is the questions:
- What is the default texture play a role in? 
- Just bind them to TextureUnit at the stage of `Context` initialization because the specification requires? 
- Should it be skipped data copy when default texture is active?
- What will happen when `glBindTexture(GL_TEXTURE_2D, 0); glTexImage2D(some valid pixels);`? Will it be ignored for 0 is active?

**Comment by abasilak** [comment]
`glBindtexture(GL_TEXTURE_2D, 0)` gets you the default texture object; it does not mean disable texturing entirely. Now texturing from the default object results in the usual operation, just on a texture object that you have created yourself. The initial texture object is initially incomplete, so unless you modify it, it will behave following the 'incomplete rules' : sampling from an incomplete texture will return (0,0,0,1).

**Comment by Michael-Lfx** [comment]
It seems *meaningless* that even if driver copies pixel data passed from user. If it just returns black color in normal draw calls.

**Comment by abasilak** [comment]
GLOVE does copies pixel data (passed from user) to the driver when texture is incomplete: https://github.com/Think-Silicon/GLOVE/blob/60c0885b7ff0480d37d7c28a82b0792d4e79d880/GLES/source/resources/shaderProgram.cpp#L1181

**Comment by Michael-Lfx** [comment]
The question is that could it the copy operation be skipped?

**Comment by abasilak** [comment]
Sorry. I forgot to write **NOT** in my previous comment.
