### ISSUE TITLE
Behavior doesn't match each other

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#52]
According to specification both Buffer Object and Renderbuffer Object will not provide default object. However, it seems that there is also no description about `target` and `GL_INVALID_VALUE` comparison. Therefore I think maybe one of the following implementation need refinement.

https://github.com/Think-Silicon/GLOVE/blob/60c0885b7ff0480d37d7c28a82b0792d4e79d880/GLES/source/context/contextRenderBuffer.cpp#L42-L61

https://github.com/Think-Silicon/GLOVE/blob/60c0885b7ff0480d37d7c28a82b0792d4e79d880/GLES/source/context/contextBufferObject.cpp#L36-L47

**Comment by abasilak** [comment]
Why?

`mResourceManager->GetRenderbuffer(renderbuffer)` returns the renderbuffer object which corresponds to the identifier _renderbuffer_. If not, it creates a new renderbuffer object with target equals to 'GL_INVALID_VALUE'. In case of value _zero_ input (where there is no default renderbuffer object), we effectively unbind any object previously bound:
https://github.com/Think-Silicon/GLOVE/blob/60c0885b7ff0480d37d7c28a82b0792d4e79d880/GLES/source/context/contextRenderBuffer.cpp#L36-L39

The current buffer object binding implementation also follows the same functionality.

**Comment by Michael-Lfx** [comment]
To be more precise, what I am confused is that BufferObject does not compare to  `GL_INVALID_VALUE` and RenderBuffer does. GLES specification indicates that no default value of them exist. Should they both add `object->GetTarget() == GL_INVALID_VALUE` statement or remove it from RenderBuffer. @abasilak

**Comment by Michael-Lfx** [comment]
Thank you Doctor.
