### ISSUE TITLE
Optimize DeleteBuffers

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#53]
https://github.com/Think-Silicon/GLOVE/blob/c13b36c40abfb18b2b482c0708ce0fc9fb961634/GLES/source/context/contextBufferObject.cpp#L119-L150

The `Finish()` is called early when the WriteFBO is in draw state. Meanwhile delete method of other objects like Texture is called in loop when they are one of the attachment of WriteFBO. In my opinion, we also can track which buffer object is been used in current draw call and we can delete them without `Finish()` if they are not used in that. It will introduce more complexity by doing this.

**Comment by dgeorg79** [comment]
Well, the early finish operation was a first quick solution so as to guarantee that all pending draw operations are completed before deleting a buffer object. We are now working in a cleaner solution: When a glDelete* function is call, the relative object will be marked for later deletion. Then, a housekeeping manager will purge the object after rendering operations are finished.

I'm moving this issue to the currently running project (GLOVE v0.4)

**Comment by dgeorg79** [comment]
Yes, such a manager is necessary for late deletion of objects such as VBOs and Textures. Just wait for the commit :)

**Comment by kpontzolkova** [comment]
Closed with commit: 977db7a03e1a945a5c96954c1624336ed1a64813
