### ISSUE TITLE
GLOVE v0.3, GLFW 3.2.1: "OpenGL ES version string retrieval is broken" error

### ISSUE THREAD

**Issue by procedural** [Think-Silicon/GLOVE#65]
cc @elmindreda, you may have an insight what GLOVE people should do to get rid of this error...

Code to repro:

```c
void GLFWErrorCallback(int error, const char *description) {
  printf("Error: %s\n", description);
}

int main() {
  glfwSetErrorCallback(GLFWErrorCallback);
  glfwInit();
  glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
  glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API);
  GLFWwindow * window = glfwCreateWindow(640, 480, "", NULL, NULL);
  glfwMakeContextCurrent(window);

  glfwDestroyWindow(window);
  glfwTerminate();
}
```

Prints:

```c
Error: OpenGL ES version string retrieval is broken
```

**Comment by elmindreda** [comment]
That error is `glGetString` returning `NULL` for `GL_VERSION`, but `Context::GetString` looks fine so perhaps GLFW is doing something wrong with EGL before that point?

**Comment by procedural** [comment]
@elmindreda I assume GLFW's code is correct because it works for regular libEGL.so

Forgot to mention all the GLOVE demos work fine, but they don't use GLFW.

Right now I assume GLOVE's EGL doesn't return `GL_VERSION` string due to incomplete EGL implementation? I don't know, will debug this extensively later today.

**Comment by procedural** [comment]
I created an EGL context manually and it works with GLFW now:

```c
  glfwSetErrorCallback(GLFWErrorCallback);
  glfwInit();
  glfwWindowHint(GLFW_RESIZABLE, 0);
  glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
  GLFWwindow * window = glfwCreateWindow(700, 700, "", NULL, NULL);

  EGLDisplay display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
  EGLint major = 0;
  EGLint minor = 0;
  EGLBoolean status = eglInitialize(display, &major, &minor);
  EGLint numConfigs = 0;
  status = eglGetConfigs(display, NULL, 0, &numConfigs);

  EGLint attribs[] = {
     EGL_RED_SIZE,     8,
     EGL_GREEN_SIZE,   8,
     EGL_BLUE_SIZE,    8,
     EGL_STENCIL_SIZE, 8,
     EGL_DEPTH_SIZE,   16,
     EGL_NONE
  };
  EGLConfig config = NULL;
  status = eglChooseConfig(display, attribs, &config, 1, &numConfigs);

  EGLSurface surface = eglCreateWindowSurface(display, config, glfwGetX11Window(window), NULL);

  EGLint contextAttribs[] = {
    EGL_CONTEXT_CLIENT_VERSION, 2,
    EGL_NONE
  };
  EGLContext context = eglCreateContext(display, config, NULL, contextAttribs);
  status = eglMakeCurrent(display, surface, surface, context);

  // ...

  eglSwapBuffers(display, surface);
```

So really this issue is a minor one...

**Comment by procedural** [comment]
Adding to the code above:
```c
const char * version = glGetString(0x1F02); // GL_VERSION
```
returns `version` string:
```c
OpenGL ES 2.0
```

**Comment by elmindreda** [comment]
The problem is likely that GLFW, which loads both the EGL and GLES libraries itself with `dlopen`, finds the GLOVE EGL library and the Mesa (or another unrelated) GLES library. When I built GLOVE and made a `libEGL.so.1` symlink I got the error above. When I also made a `libGLESv2.so.2` symlink, context creation via GLFW worked perfectly.

As an alternative to setting up symlinks or renaming the files you also can build GLFW with the `_GLFW_EGL_LIBRARY` and `_GLFW_GLESV2_LIBRARY` macros defined as strings you wish it to use instead of `"libEGL.so.1"` and `"libGLESv2.so.2"`.

**Comment by dgeorg79** [comment]
2 comments from GLOVE team:

1. GLOVE is designed to produce libEGL.so and libGLESv2.so binaries in installation phase and no additional links. I don't think it is necessary to add any link. 
2. GLOVE demos use eglut, but, given this issue, I think it would be useful to add some examples GLFW as well.

Your feedback will be appreciated,
thanks

**Comment by procedural** [comment]
> When I also made a libGLESv2.so.2 symlink, context creation via GLFW worked perfectly.

Ah, I see, I linked GLOVE's libGLESv2.so directly to my program, [but I forgot that it means absolutely nothing in linux](https://github.com/procedural/linux_shared_library_catastrophe/tree/master/1) and the program can go find the library from somewhere else.

Issues can be closed then!

@dgeorg79 
> I think it would be useful to add some examples GLFW as well

Would be great!
