### ISSUE TITLE
For desktops? Readme, meterials, etc. could be more clear about what this is for. 

### ISSUE THREAD

**Issue by mick-p1982** [Think-Silicon/GLOVE#66]
OpenGL ES doesn't work on a Windows desktop. Is GLOVE a way to have an ES API? Or is it for "Windows" phones? Is it comparable to efforts to emulate ES with desktop OpenGL? This is my first question, but it's not answered by your products description. Thanks.

Bonus question (edit) Shouldn't there be a DLL or something that is in the Release section; that enables OpenGL ES over Vulkan in software that makes use of GLOVE?

**Comment by dgeorg79** [comment]
GLOVE has been designed as a cross platform middle-ware, however it is not yet ported to Windows (currently supported OS: Linux and Android). What needs to be done is to allow compilation and linking in a Windows OS environment as well as run some first demos. 

Unfortunately, our short-term plans are restricted to other areas such as supporting more Window platforms (e.g. Wayland) and covering 100% KHRONOS Conformance tests.

How important is for you to support Windows OS? Have you any use case in your mind?

**Comment by mick-p1982** [comment]
I think it's important (to me) for the product description (here) to be clear about this matter.

Personally, I would like it if there were OpenGL ES modules that work like vendor drivers on desktops. Even if they are virtual. I am not a fan of OpenGL but the ES variants are much cleaner and more modern (less extension baggage, etc.) and so I think it would be a positive development if ES were somehow straightforward for desktop software to use.  Both because it's a better API and because code written in ES is more portable than code written in OpenGL.

(It bothers me that Khronos doesn't have a charitable arm that works on parity for desktop, since desktop is the legacy PC platform and what developers use most. Open vector-graphic standard implementation on desktop is another area that has not developed since standards were introduced for phone devices.)

I can't say more, other than if there were DLL/SO files for OpenGL ES on desktop that used Vulkan I would definitely consider using them for work--even if not performant/conformant. Especially if it looked like giving them a test run is not a multi-day installation ordeal.

**Comment by dgeorg79** [comment]
Well, you're right! We will update the GLOVE documentation so as to clearly state the so far supported platforms as well as what's planned for the future versions.

For the moment, Windows OS support is not in our short-term plans. However, if anyone in the community would like to contribute into this area, Think Silicon could support him/ her from SW design perspective.

**Comment by dgeorg79** [comment]
Some update on this issue. We recently supported WAYLAND platform on Linux. I believe that porting GLOVE to Windows OS will need an extension in GLOVE/EGL, similar to what was need for WAYLAND. 

I  have already started porting GLOVE to Windows via Visual Studio 19. I will update you when I have something worthwhile to try.

**Comment by dgeorg79** [comment]
Hi,

porting to windows has been covered by #81 

You can test GLOVE on Windows, after 5aef5a06542c374be322971c5bd2c870aecc3de4

We will be more than happy to receive feedback

**Comment by mick-p1982** [comment]
I definitely will ... get around to it. Can you comment on how portable it is, off Windows? Is Linux desktop covered? Apple?

**Comment by mick-p1982** [comment]
EDITED: Does GLOVE fallback to native OpenGL if requested? I'm worried about losing Indirect GLX functionality, or having to maintain separate pathways. 

Off-topic: Since GLOVE is concerned with emulating legacy technology, I wonder if there is any possibility it can do something like IGLX or if it would be difficult to emulate it, plus adding new features that it lacks and probably will never see, like say using a sideband protocol to send ES commands over network to be rendered locally on an X server drawing surface.

**Comment by mick-p1982** [comment]
I think I may be at a loss because my chipset doesn't have Vulkan drivers. I was under the impression Vulkan was engineered as a replacement for OpenGL but it seems like if it's not implemented for all chipsets Vulkan is only accessory software until all of the chips without it die out.

https://www.intel.com/content/www/us/en/support/articles/000005524/graphics-drivers.html

I realized not all systems had Vulkan, but did not realize systems that did were still segregated by chipset, sorry.

**Comment by dgeorg79** [comment]
To reply to your questions:

1. GLOVE is tested on Linux desktop, Linux Embedded systems, Android systems and now Windows. You can refer to the table here: https://github.com/Think-Silicon/GLOVE#tested-with-the-following-configurations to see all of the tested configurations.
    We plan to finish porting to Mac in a couple of weeks, see #80.

2. GLOVE is a pure OpenGL ES to Vulkan translator solution, so it doesn't provide any fallback solution, like native OpenGL. It think you can utilize other SW frameworks that do that, setting GLOVE as a backend.

3. I hope you can test Vulkan with another chipset sometime, feedback would be appreciated. I have tested with NVIDIA Vulkan driver, as referred in the last row of the above table

**Comment by mick-p1982** [comment]
Thank you. I have to recalibrate my outlook on Vulkan now by several more years. 

Is there an "other SW frameworks" list somewhere? Thanks again! If this topic inspired someone to work on Windows desktop support it's still totally worth it I think. As a fellow developer/maintainer I'd be glad to have that under my belt.

The OpenGL/Vulkan world really needs a grand unified system. It's splintered to a degree it's too difficult to fathom.

**Comment by dgeorg79** [comment]
You can try [glfw](https://github.com/glfw/glfw) or [bgfx](https://github.com/bkaradzic/bgfx). I'm sure you can find a few other similar SW frameworks in GitHub.

GLOVE is a pure translator middleware from OpenGL ES to Vulkan which could be utilized to support  OpenGL ES applications to run on Vulkan capable GPUs.

Thanks for opening this issue, you inspired us to work on GLOVE portability, which is undoubtedly worthwhile.

I'm now closing the issue. If you have any objections, please let us know.
