### ISSUE TITLE
Support Wayland Platform

### ISSUE THREAD

**Issue by dgeorg79** [Think-Silicon/GLOVE#69]
Create Wayland backend in EGL and test it

**Comment by Michael-Lfx** [comment]
Hello. Is the project still in development? cc @dgeorg79

**Comment by dgeorg79** [comment]
Yes, it is, current priorities are Wayland backend and EGL

**Comment by Michael-Lfx** [comment]
Thank you. When will you support macOS/iOS?

**Comment by dgeorg79** [comment]
Not yet plan for this, unfortunately. But as I was saying in an other issue, Think Silicon can help from design perspective, people who would like to contribute in this direction.

**Comment by dgeorg79** [comment]
resolved with 605394dbe6512c70b82d9a93eb990203f20e9947
