### ISSUE TITLE
Textures should not implicitly convert all host data to RGBA8

### ISSUE THREAD

**Issue by kvarcg** [Think-Silicon/GLOVE#7]
Currently, all texturing operations are implicitly converted to GL_RGBA and GL_UNSIGNED_BYTE (VK_FORMAT_R8G8B8A8_UNORM) before submitted to Vulkan. This operation causes memory and performance overhead and should be removed for all formats that are supported in both GL and Vulkan.

**Comment by abasilak** [comment]
Solved with commit ff0ee24e6a1ca8266e67e402326ec2b1ef47c85f
