### ISSUE TITLE
Q: Why use double buffering instead of triple buffering 

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#74]
https://github.com/Think-Silicon/GLOVE/blob/30635f205524e07c044c0231b291d207267f8f48/EGL/source/platform/vulkan/vulkanWindowInterface.cpp#L214-L215

- What's the advantage of double buffering if current platform supports triple buffering? 
- Should we replace `2` with `GLOVE_NUM_COMMAND_BUFFERS` even if using double buffering?

**Comment by dgeorg79** [comment]
Double buffering was a first choice for GLOVE, for simplicity reasons. In the future we should consider supporting triple buffering as well, but this is not a priority for now.
