### ISSUE TITLE
Is singleton VKContext faster than instance per EGLContext?

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#75]
Currently `VKContext` is using a singleton pattern. Will it be faster or save memory than creating an instance per EGLContext instance or that will make the codebase complex?

**Comment by dgeorg79** [comment]
There is a reason for this. VulkanAPI::Context hides a vulkan instance (VkInstance) which is preferable to be unique per application. Therefore VulkanAPI::Context is implemented as a singleton
