### ISSUE TITLE
Replace glFinish with glFlush in eglSwapBuffers

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#76]
https://github.com/Think-Silicon/GLOVE/blob/6dd9c391509da76a87275fd94955710de89d5a66/GLES/source/context/contextRendering.cpp#L436

As asked in #27 previously, I think `eglSwapBuffers()` can use `glFlush` most of the time with triple buffering. It only needs `glFinish` to throttle when CPU is sending faster than GPU can handle or occupied memories out of our expectation.

**Comment by Michael-Lfx** [comment]
I have tested that it's alright to replace `glFinish` with `glFlush` in `eglSwapBuffers` if we handle status of the write framebuffer.

**Comment by dgeorg79** [comment]
It would make sense to investigate whether it is worthwhile do this enhancement to boost performance, however this is not a priority now.
