### ISSUE TITLE
Wrong default EGL API value

### ISSUE THREAD

**Issue by jekstrand** [Think-Silicon/GLOVE#8]
The EGL spec says:

> The initial value of the current rendering API is `EGL_OPENGL_ES_API`, unless OpenGL ES is not supported by an implementation, in which case the initial value is `EGL_NONE`.

However, if you try to create a context with GLOVE without explicitly setting the API it crashes in an unreachable.

**Comment by kvarcg** [comment]
You are correct, thank you for spotting this. I added a fix.

**Comment by jekstrand** [comment]
Seems to work for me.
