### ISSUE TITLE
Port GLOVE to Apple

### ISSUE THREAD

**Issue by dgeorg79** [Think-Silicon/GLOVE#80]

**Comment by dgeorg79** [comment]
GLOVE is partially supported on Mac! triangle2d_one_color example has been successfully tested!

Check commit e7fb6e8e56cfcfba4fca56373ff2affc3c8e0887.

**Comment by Platin21** [comment]
Wouldn’t it work better to not use the half backed Vulkan layers and just use Metal? 
I guess it’s to different.

**Comment by dgeorg79** [comment]
Do you mean directly translate GL ES to Metal? This would be nice, but in the context of another project. GLOVE was created to support GL ES applications on Vulkan capable GPUs, without the need of a native GL ES driver. As far as I know, Vulkan is not yet supported in Mac devices, therefore there's a need for an extra conversion (Vulkan to Metal) so that GLOVE is able to run on Mac.

**Comment by Platin21** [comment]
I can understand why it doesn’t make a lot of sense to use metal directly. Doesn’t the MVK stuff already include a Window with there custom view?

**Comment by dgeorg79** [comment]
GLOVE takes care about that when creating a Vulkan/WSI Surface at  [WSIMacOS.mm.](https://github.com/Think-Silicon/GLOVE/blob/master/EGL/source/platform/vulkan/WSIMacOS.mm#L84). Vulkan surface for MacOS hosts a custom NSView (see [Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkMacOSSurfaceCreateInfoMVK.html)) which must have been created by the application. In GLOVE Demos the main window view is mapped to EGL Surface (and eventually to Vulkan Surface) in [GLOVE/Demos/eglut](https://github.com/Think-Silicon/GLOVE/blob/master/Demos/eglut/eglut_macos.m#L61)

**Comment by dgeorg79** [comment]
All GLOVE demos play on Mac with 40a497c1583bef800701ab373ebff0627f16f9ae. 

Closing this issue now
