### ISSUE TITLE
crash when debug model

### ISSUE THREAD

**Issue by 82157402** [Think-Silicon/GLOVE#87]
void TParseContext::structTypeCheck(const TSourceLoc& /*loc*/, TPublicType& publicType)
{
    const TTypeList& typeList = *((publicType.userDef)->getStruct());
  ....
}
typeList is null  when debug model.
I donot make sure the reason . becase these code are glslang code.
who know?thankyou

**Comment by 82157402** [comment]
![image](https://user-images.githubusercontent.com/12945580/72967078-680d2900-3dfb-11ea-9967-3e815c02f5d0.png)

**Comment by dgeorg79** [comment]
Hi,

    I think I have seen the same error in the past. I will run a debug build on Windows and try to fix

**Comment by dgeorg79** [comment]
I managed to reproduced the problem, so we are in the same page now! 

Most likely it is a compilation issue, similar to an older problem solved by 30635f205524e07c044c0231b291d207267f8f48. It's a bit weird but we do our best to resolve.

**Comment by dgeorg79** [comment]
This was a really ugly bug in python script. It works now in our environment for Windows Debug build. We also changed cmake so as to support both Release and Debug builds for Windows simultaneously.

Could you test with commit b044239cccaaab52663dad34117c7f8b33ea8eb6? (Need to re-run update_external_sources.py as well)

**Comment by dgeorg79** [comment]
Closing the issue now
